name: Publish itsmorio/ui OCI image

on:
  release:
    types: [published]

jobs:
  build_and_push_to_registry:
    name: Build & Publish OCI Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build & Publish the OCI image
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
        run: 'npm run ci:build.ui publish'
